#!/usr/bin/env node
// 读取 theme.config.json，生成 src/client/theme/generated.ts（字面量 import），
// 素材缺失时图片用占位兜底、视频置 null，构建不崩。
// 用法:
//   pnpm bundle        -> node scripts/build-theme.mjs && tsc -b && tsdown
//   pnpm assets:check  -> node scripts/build-theme.mjs --check  (只检查素材完整性)
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve, relative } from 'node:path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const pkgRoot = resolve(__dirname, '..')
const localConfigPath = resolve(pkgRoot, 'theme.config.local.json')
const configPath = existsSync(localConfigPath)
  ? localConfigPath
  : resolve(pkgRoot, 'theme.config.json')
const generatedPath = resolve(pkgRoot, 'src/client/theme/generated.ts')
const defaultsDir = resolve(pkgRoot, 'defaults')
const themeDir = resolve(pkgRoot, 'src/client/theme')

// 1x1 透明 PNG，作为图片素材缺失时的兜底占位
const PLACEHOLDER_PNG = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+M8AAAMBAQAY3Y2wAAAAAElFTkSuQmCC'

function ensurePlaceholder() {
  if (!existsSync(defaultsDir)) mkdirSync(defaultsDir, { recursive: true })
  const p = resolve(defaultsDir, 'placeholder.png')
  if (!existsSync(p)) writeFileSync(p, Buffer.from(PLACEHOLDER_PNG, 'base64'))
  return p
}

const isVideo = (rel) => /\.(mp4|webm)$/i.test(rel)
const toImportPath = (abs) => relative(themeDir, abs).split('\\').join('/')

if (!existsSync(configPath)) {
  console.error(`[build-theme] 缺少 theme.config.json: ${configPath}`)
  process.exit(1)
}

const cfg = JSON.parse(readFileSync(configPath, 'utf8'))
const assets = cfg.assets || {}
const checkOnly = process.argv.includes('--check')

const missing = []
const imports = []
const entries = ['export const assetUrls = {']

for (const [key, rel] of Object.entries(assets)) {
  const abs = resolve(pkgRoot, rel)
  if (rel && existsSync(abs)) {
    imports.push(`import ${key} from '${toImportPath(abs)}'`)
    entries.push(`  ${key}: ${key},`)
  } else {
    missing.push(rel)
    if (isVideo(rel)) {
      entries.push(`  ${key}: null,`)
    } else {
      const ph = ensurePlaceholder()
      imports.push(`import ${key} from '${toImportPath(ph)}'`)
      entries.push(`  ${key}: ${key},`)
    }
  }
}
entries.push('}')

if (missing.length) {
  console.warn('[build-theme] ⚠️ 以下素材缺失，已用占位兜底（构建不会失败）:')
  for (const m of missing) console.warn(`   - ${m}`)
} else {
  console.log('[build-theme] ✅ 所有素材齐全')
}

if (checkOnly) {
  process.exit(missing.length ? 1 : 0)
}

const out = [
  '// AUTO-GENERATED by scripts/build-theme.mjs — DO NOT EDIT BY HAND',
  '// 重新生成: pnpm bundle    仅检查素材: pnpm assets:check',
  '',
  ...imports,
  '',
  ...entries,
  '',
].join('\n')

writeFileSync(generatedPath, out)
console.log('[build-theme] ✅ 已生成 src/client/theme/generated.ts')
